config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  resources :roles
  resources :projects
  resources :employees
  resources :companies
  post '/assign_periods', to: 'employees#assign_projects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'search', to: 'companies#search'
  get '/search' => 'pages#search', :as => 'search_page'

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :comments, as: :commentable

	def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/comment-old.rb
class Comment < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy 
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :employees
	has_many :projects
	validates_length_of :employees, :maximum => 50
	validates :company_name, presence: true
	validates_length_of :company_name, minimum: 3
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["company_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end 

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :company, optional: true
	has_one :role
	has_many :employees_projects
	has_many :projects, through: :employees_projects
	validates :employee_name, presence: true
	validates_length_of :employee_name, minimum: 3, maximum: 15, allow_blank: true
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["employee_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
	belongs_to :employee
	belongs_to :project
end

app/models/page.rb
class Page < ApplicationRecord
	def self.search
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :employees_projects
	has_many :employees, through: :employees_projectss
	validates_length_of :project_name, minimum: 3
	validates :project_name, presence: true

	def self.search(search)
    if search
      where(["project_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end 
end

app/models/role.rb
class Role < ApplicationRecord
	belongs_to :employee
	validates_uniqueness_of :role_name, uniqueness: { case_sensitive: false }
	validates_presence_of :role_name
	validates_length_of :role_name, minimum: 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable
  attr_accessor :employee_name, :company_id, :image, :dob, :gender
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee

  after_create :create_employee

  def create_employee
  	employee = Employee.new(employee_name: self.employee_name, dob: self.dob, gender: self.gender, company_id: self.company_id, image: self.image)
  	employee.save
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    if params[:search]
      @employees = Employee.search(params[:search]) 
    else 
      @employees = Employee.all
    end 
    
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee_projects = @employee.employees_projects
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  def assign_projects
    @employee_projects = EmployeesProject.create(project_id: params[:project_id], employee_id: params[:employee_id])
    redirect_to employee_path(params[:employee_id])
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:employee_name, :company_id, :image, :dob, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper-old.rb
module CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_assign_projects.html.erb
+  def create_student
+    employee = Employee.find_by_id(params[:project][:employees_projects])
+    employees_project = EmployeesProject.where(employee_id: params[:project][:employees_projects], project_id: @project.id).first
+    if employee.present? && employees_project.nil?
+      EmployeesProject.create(employee_id: employee.id, project_id: @project.id)
+    end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table style="width:65%;height:90%;" align="center">
    <tr style="background-color:#32A9EE;color:white;">
      <td><%= form.label :employee_name %></td>
      <td><%= form.text_field :employee_name %></td>
    </tr>
    <br>
    <tr style="background-color:#32A9EE;color:white;">
      <td><%= form.label :company_name %></td>
      <td><%= form.collection_select :company_id, Company.order(:company_name),:id,:company_name, include_blank: true %></td>
    </tr>
    <tr>
      <td><%= form.label :image %></td>
      <td><%= form.file_field :image%></td>
      <tr>
    <tr>
      <td><%= form.label :dob %></td>
      <td><%= form.date_field :dob%></td>
    </tr>
    <tr>
      <td><%= form.label :gender %></td>
      <td><%= form.select(:gender, [ 'Male', 'Female', 'Other' ], {}, { :class => 'select' }) %></td>
    </tr>
    <div class="actions">
      <td colspan="2"><button><%= form.submit %></button></td>
    </div>
  </table>
<% end %>

app/views/employees/edit.html.erb
<div align="center">
	<h1>Editing Employee</h1>
</div>
<div align="center">
	<%= render 'form', employee: @employee %>
</div>
<div align="center">
	<button><%= link_to 'Show', @employee %> |
	<%= link_to 'Back', employees_path %></button>
</div>

app/views/employees/index.html.erb
<div align="center">
<%= form_tag employees_path, :method => "get" do %>   
<%= text_field_tag :search, params[:search] %>   
<%= submit_tag "Search" %>  
<% end %>
  <% if @employees.empty? %>
  <h1>Oops! No Result Found!</h1>
<%else%>
  <caption><h2><ins><i>EMPLOYEES LIST</i></ins></h2></caption>
</div>
<p id="notice"><%= notice %></p>
<table class="table" style="width:65%;height:90%;" align="center">
  <tr class="bdrfirst">
    <th>Employee</th>
    <th>DOB</th>
    <th>gender</th>
    <th>Role</th>
    <th>Project Count</th>
    <th>image</th>
    <th>Actions</th>
  </tr>
  <tbody>
    <% @employees.each do |employee| %>
      <tr style="background-color:#32A9EE;color:white;">
        <td><%= employee.employee_name %></td>
        <td><%= employee.dob%></td>
        <td><%= employee.gender%></td>
        <td><%= employee.role.try(:role_name) %></td>
        <td><%= employee.employees_projects.count %></td>
        <td><img src="<%= employee.image.url %>" class='img-ur'></td>
        <td><%= link_to '| Show |', employee %>
            <%= link_to '| Edit', edit_employee_path(employee) %>
            <%= link_to '| Destroy |', employee, method: :delete, data: { confirm: 'Are you sure?' } %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>
<div align="center">
  <button><%= link_to 'New Employee', new_employee_path %></button>
</div>

app/views/employees/new.html.erb
<div align="center">
	<h1>New Employee</h1>
</div>
<%= render 'form', employee: @employee %>
<br>
<div align="center">
	<button><%= link_to 'Back', employees_path %></button>
</div>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
	<%= @employee.employee_name %><br/>
	<%= image_tag (@employee.image_url), :size => "260x180" %><br/>
	<%= @employee.dob %><br/>
	<%= @employee.gender%>
	<%= form_with url: assign_periods_path do |f| %>
  	<%= f.collection_select :project_id, Project.order(:project_name),:id,:project_name, include_blank: true, class: "form-control" %>
  	<%= f.hidden_field :employee_id, value: @employee.id %>
	  <%= f.submit %>
  <%end%>
	<table class="table">
		<tr>
			<th>
				Project Name
			</th>
		</tr>
		<tbody>
			<% @employee.employees_projects.each do |obj| %>
				<tr>
					<td><%= obj.project.project_name %></td>
					<td><%#= link_to 'Show', project %></td>
	        <td><%#= link_to 'Edit', edit_project_path(project) %></td>
	        <td><%#= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				</tr>
			<%end%>
		</tbody>
	</table>
	<button><%= link_to 'Edit', edit_employee_path(@employee) %> |
	<%= link_to 'Back', employees_path %></button>
</div>