config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  resources :roles
  resources :projects
  resources :employees
  resources :companies
  post '/assign_periods', to: 'employees#assign_projects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'search', to: 'companies#search'
  get '/search' => 'pages#search', :as => 'search_page'

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :comments, as: :commentable

	def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/comment-old.rb
class Comment < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy 
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :employees
	has_many :projects
	validates_length_of :employees, :maximum => 50
	validates :company_name, presence: true
	validates_length_of :company_name, minimum: 3
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["company_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end 

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :company, optional: true
	has_one :role
	has_many :employees_projects
	has_many :projects, through: :employees_projects
	validates :employee_name, presence: true
	validates_length_of :employee_name, minimum: 3, maximum: 15, allow_blank: true
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["employee_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
	belongs_to :employee
	belongs_to :project
end

app/models/page.rb
class Page < ApplicationRecord
	def self.search
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :employees_projects
	has_many :employees, through: :employees_projectss
	validates_length_of :project_name, minimum: 3
	validates :project_name, presence: true

	def self.search(search)
    if search
      where(["project_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end 
end

app/models/role.rb
class Role < ApplicationRecord
	belongs_to :employee
	validates_uniqueness_of :role_name, uniqueness: { case_sensitive: false }
	validates_presence_of :role_name
	validates_length_of :role_name, minimum: 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable
  attr_accessor :employee_name, :company_id, :image, :dob, :gender
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee

  after_create :create_employee

  def create_employee
  	employee = Employee.new(employee_name: self.employee_name, dob: self.dob, gender: self.gender, company_id: self.company_id, image: self.image)
  	employee.save
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments-old/_comment.html.erb
<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User_id:</strong>
  <%= @comment.user_id %>
</p>

app/views/comments-old/_form.html.erb
<p><%= link_to 'blog_page', blogs_path %></p>

<h2>Add a comment:</h2>
<%= form_with model: @comment, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
  </p>
    <p>
    <%= form.hidden_field :user_id, value:"#{current_user.id}" %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments-old/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments-old/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
          <% if current_user.id == comment.user_id %>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>
<p><%= link_to 'blog_page', blogs_path %></p>

app/views/comments-old/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments-old/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<p>
  <strong>User_id:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>
<p><%= link_to 'blog_page', blogs_path %></p>

app/views/layouts/_header.html.erb
<body>
<div class="menu-bar">
	<ul>
		<li class="active"><a href="/">Home</a></li>
		<li><%= link_to 'Company', companies_path %></li>
		<li><%= link_to 'Employee', employees_path %></li>
		<li><%= link_to 'Project', projects_path %></li>
		<li><%= link_to 'Blog' , blogs_path %></li>
		<li>
			<% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    	<% else %>
        <%= link_to 'Sign in', new_user_session_path %>
    	<% end %>
    </li>
		<h6>
			<% if user_signed_in? %>
        Signed in as <%= current_user.email %>
    	<% end %>
    </h6>
	</ul>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>company-project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %> 
    <%= yield %>
  </body>
</html>