config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    resources :comments
  end
  resources :comments do
    resources :comments
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'welcome/index'
  resources :roles
  resources :projects
  resources :employees
  resources :companies
  post '/assign_periods', to: 'employees#assign_projects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'search', to: 'companies#search'
  get '/search' => 'pages#search', :as => 'search_page'

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :comments, as: :commentable

	def self.search(search)
    if search
      where(["title LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/comment-old.rb
class Comment < ApplicationRecord

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy 
end

app/models/company.rb
class Company < ApplicationRecord
	has_many :employees
	has_many :projects
	validates_length_of :employees, :maximum => 50
	validates :company_name, presence: true
	validates_length_of :company_name, minimum: 3
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["company_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end 

app/models/employee.rb
class Employee < ApplicationRecord
	belongs_to :company, optional: true
	has_one :role
	has_many :employees_projects
	has_many :projects, through: :employees_projects
	validates :employee_name, presence: true
	validates_length_of :employee_name, minimum: 3, maximum: 15, allow_blank: true
	mount_uploader :image, ImageUploader

	def self.search(search)
    if search
      where(["employee_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end
end

app/models/employees_project.rb
class EmployeesProject < ApplicationRecord
	belongs_to :employee
	belongs_to :project
end

app/models/page.rb
class Page < ApplicationRecord
	def self.search
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :employees_projects
	has_many :employees, through: :employees_projectss
	validates_length_of :project_name, minimum: 3
	validates :project_name, presence: true

	def self.search(search)
    if search
      where(["project_name LIKE ?","%#{search}%"])
    else
      all
    end 

  end 
end

app/models/role.rb
class Role < ApplicationRecord
	belongs_to :employee
	validates_uniqueness_of :role_name, uniqueness: { case_sensitive: false }
	validates_presence_of :role_name
	validates_length_of :role_name, minimum: 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable
  attr_accessor :employee_name, :company_id, :image, :dob, :gender
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :employee

  after_create :create_employee

  def create_employee
  	employee = Employee.new(employee_name: self.employee_name, dob: self.dob, gender: self.gender, company_id: self.company_id, image: self.image)
  	employee.save
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    if params[:search]
      @companies = Company.search(params[:search]) 
    else 
      @companies = Company.all
    end
  end
  # GET /companies/1
  # GET /companies/1.json
  def show
  
    @company_employees = @company.employees
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
   @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:company_name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper-old.rb
module CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2><ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table style="width:65%;height:90%;" align="center">
    <tr style="background-color:#32A9EE;color:white;">
      <td><%= form.label :company_name %></td>
      <td><%= form.text_field :company_name %></td>
    </tr>
    <tr>
      <td><%= form.label :image %></td>
      <td><%= form.file_field :image%></td>
      <tr>
    <br>
    <tr>
      <div class="center">
        <td colspan="2"><button><%= form.submit %></button></td>
      </div>
    </tr>
  </table>
<% end %>

app/views/companies/edit.html.erb
<div align="center">
	<h1>Editing Company</h1>
</div>
<%= render 'form', company: @company %>
<br>
<div align="center">
	<button>
		<%= link_to 'Show', @company %> |
		<%= link_to 'Back', companies_path %>
	</button>
</div>

app/views/companies/index.html.erb
<div align="center">
<%= form_tag companies_path, :method => "get" do %>   
<%= text_field_tag :search, params[:search] %>   
<%= submit_tag "Search" %>  
<% end %>
<% if @companies.empty? %>
  <h1>Oops! No Result Found!</h1>
<%else%>
  <caption><h2><ins><i>COMPANY LIST</i></ins></h2></caption>
</div>
<div align="center">
  <button ><%= link_to 'New Company', new_company_path %></button>
</div>
<p id="notice"><%= notice %></p>
  <table class="table" style="width:65%;height:90%;" align="center">
    <tr class="bdrfirst">
      <th>Company</th>
      <th>Employee</th>
      <th>Image</th>
      <th>Actions</th>
    </tr>
    <tbody>
      <% @companies.each do |company| %>
        <tr  style="background-color:#32A9EE;color:white;">
          <td><%= company.company_name %></td>
          <td><%= company.employees.count %></td>
          <td><img src="<%= company.image.url %>" class='img-ur'></td>
          <td><%= link_to '|Show |', company %>
              <%= link_to 'Edit', edit_company_path(company) %>
              <%= link_to '|Destroy|', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %> 
<br>

app/views/companies/new.html.erb
<div align="center">
	<h1>New Company</h1>
</div>
<div align="center">
	<button><%= link_to 'Back', companies_path %></button>
</div>
<%= render 'form', company: @company %>
<br>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
	<%= @company.company_name %><br/>
	<%= image_tag (@company.image_url), :size => "260x180" %>
	<table class="table">
		<tr>
			<th>Employee Name</th>
		</tr>
		<tbody>
			<% @company_employees.each do |employee| %>
				<tr>
					<td><%= employee.employee_name %></td>
					<td><%= link_to '| Show |', employee %>
			      <%= link_to '| Edit', edit_employee_path(employee) %>
			      <%= link_to '| Destroy |', employee, method: :delete, data: { confirm: 'Are you sure?' } %>
			    </td>
				</tr>
			<%end%>
		</tbody>
	</table>
	<button><%= link_to 'Edit', edit_company_path(@company) %> |
	<%= link_to 'Back', companies_path %></button>
</div>